name: Test

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.1
      - name: Install modules
        run: pnpm install
      - name: Run unit tests
        run: pnpm test

  end-to-end-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.1
      - name: Install modules
        run: pnpm install
      - name: Run end-to-end tests
        run: pnpm cypress:run
